version: '3.9'

services:

  redis:
    image: redis:alpine3.13
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
  web:
    build: .
    command: "./run_web.sh"
    image: web
    links:
      - redis
      - selenium
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  worker:
    build: .
    command: "./run_celery.sh"
    image: web
    depends_on:
      - web
      - redis
      - selenium
